### ISSUE TITLE
Not able to register user and login

### ISSUE THREAD

**Issue by kaprat** [chat-sdk/chat-sdk-android#102]
Code :

Map<String, Object> data = AbstractNetworkAdapter.getMap(
                        new String[]{BDefines.Prefs.LoginTypeKey, BDefines.Prefs.LoginEmailKey, BDefines.Prefs.LoginPasswordKey },
                        BDefines.BAccountType.Register, etEmail.getText().toString(), etEmail.getText().toString());

                BNetworkManager.sharedManager().getNetworkAdapter()
                        .authenticateWithMap(data).done(new DoneCallback<Object>() {
                    @Override
                    public void onDone(Object o) {
                        Log.e("Success","Success");
                    }
                }).fail(new FailCallback<BError>() {
                    @Override
                    public void onFail(BError bError) {
                        Log.e("Failure","Failure");
                    }
                });

Error Getting :

Attempt to invoke virtual method 'org.jdeferred.Promise com.braunster.chatsdk.network.AbstractNetworkAdapter.authenticateWithMap(java.util.Map)' on a null object reference  at 

LoginActivity$2.onClick(LoginActivity.java:174)
                                                                           at android.view.View.performClick(View.java:4780)
                                                                           at android.view.View$PerformClick.run(View.java:19866)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Getting error in this line:  .authenticateWithMap(data).done(new DoneCallback<Object>() {

**Comment by kaprat** [comment]
i onCreate method i forgot to initialize chatsdk using below code.

        // Setup the chat
        ChatSDKUiHelper.initDefault(); // This is used for the app custom toast and activity transition

        BNetworkManager.init(getApplicationContext()); // Init the network manager

        // Adapter init.
        BChatcatNetworkAdapter adapter = new BChatcatNetworkAdapter(getApplicationContext());
        BNetworkManager.sharedManager().setNetworkAdapter(adapter); // Set the adapter to the networ
