### ISSUE TITLE
Simultaneously two image sending app gets crashed

### ISSUE THREAD

**Issue by kaprat** [chat-sdk/chat-sdk-android#104]
I am trying to send two image simultaneously, when i send one image then app works fine but as soon as i send second image then app gets crashed i have attached stack trace below. 

E/UncaughtException: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6809, result=-1, data=Intent { (has extras) }} to activity {com.annanovas.askyoo/com.braunster.chatsdk.activities.ChatSDKChatActivity}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
                                                                             at android.app.ActivityThread.access$1300(ActivityThread.java:151)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                          Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                             at android.view.ViewGroup.addView(ViewGroup.java:3718)
                                                                             at android.view.ViewGroup.addView(ViewGroup.java:3700)
                                                                             at com.github.johnpersano.supertoasts.SuperCardToast.show(SuperCardToast.java:348)
                                                                             at com.braunster.chatsdk.Utils.helper.ChatSDKUiHelper.showProgressCard(ChatSDKUiHelper.java:388)
                                                                             at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.sendingMessageToast(ChatSDKChatHelper.java:487)
                                                                             at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.sendImageMessage(ChatSDKChatHelper.java:642)
                                                                             at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.processCroppedPhoto(ChatSDKChatHelper.java:421)
                                                                             at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.handleResult(ChatSDKChatHelper.java:374)
                                                                             at com.braunster.chatsdk.activities.abstracted.ChatSDKAbstractChatActivity.onActivityResult(ChatSDKAbstractChatActivity.java:566)
                                                                             at android.app.Activity.dispatchActivityResult(Activity.java:6192)
                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617) 
                                                                             at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.annanovas.askyoo, PID: 24201
                                                                      java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6809, result=-1, data=Intent { (has extras) }} to activity {com.annanovas.askyoo/com.braunster.chatsdk.activities.ChatSDKChatActivity}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                          at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
                                                                          at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
                                                                          at android.app.ActivityThread.access$1300(ActivityThread.java:151)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                       Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:3718)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:3700)
                                                                          at com.github.johnpersano.supertoasts.SuperCardToast.show(SuperCardToast.java:348)
                                                                          at com.braunster.chatsdk.Utils.helper.ChatSDKUiHelper.showProgressCard(ChatSDKUiHelper.java:388)
                                                                          at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.sendingMessageToast(ChatSDKChatHelper.java:487)
                                                                          at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.sendImageMessage(ChatSDKChatHelper.java:642)
                                                                          at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.processCroppedPhoto(ChatSDKChatHelper.java:421)
                                                                          at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.handleResult(ChatSDKChatHelper.java:374)
                                                                          at com.braunster.chatsdk.activities.abstracted.ChatSDKAbstractChatActivity.onActivityResult(ChatSDKAbstractChatActivity.java:566)
                                                                          at android.app.Activity.dispatchActivityResult(Activity.java:6192)
                                                                          at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
                                                                          at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617) 
                                                                          at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by matheuaviczki** [comment]
This occurs because of the custom load toast "Sending" ... remove it and you will be able to send two images

**Comment by kaprat** [comment]
Yes it works i have commented sendingMessageToast(); method and now i am able to send multiple images simultaneously.

Thanks @matheuaviczki

**Comment by bensmiley** [comment]
Fixed in v4.0.
