### ISSUE TITLE
Clicking on Location App gets Crashed While sending location message

### ISSUE THREAD

**Issue by kaprat** [chat-sdk/chat-sdk-android#106]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.annanovas.askyoo, PID: 10226
                                                                      java.lang.NoSuchMethodError: No virtual method getMap()Lcom/google/android/gms/maps/GoogleMap; in class Lcom/google/android/gms/maps/MapFragment; or its super classes (declaration of 'com.google.android.gms.maps.MapFragment' appears in /data/app/com.annanovas.askyoo-1/base.apk)
                                                                          at com.braunster.chatsdk.activities.ChatSDKLocationActivity.onCreate(ChatSDKLocationActivity.java:61)
                                                                          at android.app.Activity.performCreate(Activity.java:5990)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by bensmiley** [comment]
Fixed in v4.0.
