### ISSUE TITLE
App crash sometime while sending message

### ISSUE THREAD

**Issue by baokk** [chat-sdk/chat-sdk-android#109]
I've updated BBackendless to v4.0
After that always got some problem while sending messages.

Fatal Exception: java.lang.ClassCastException: java.util.HashMap cannot be cast to com.backendless.messaging.MessageStatus
       at com.braunster.androidchatsdk.firebaseplugin.firebase.backendless.BBackendlessHandler$2.handleResponse(BBackendlessHandler.java:122)
       at com.backendless.async.message.AsyncMessage$ResponseHandler.handle(AsyncMessage.java:64)
       at com.backendless.async.message.AsyncMessage.handleCallback(AsyncMessage.java:41)
       at com.backendless.core.AndroidCarrier$1.handleMessage(AndroidCarrier.java:37)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by bensmiley** [comment]
Fixed in v4.0.
