### ISSUE TITLE
Chat crash, DaoException Property 'entityId' is not part

### ISSUE THREAD

**Issue by PgVova** [chat-sdk/chat-sdk-android#127]
**Chat crash after login or register** 
 Process: com.clearsoft.welivre, PID: 21023
                                                                       java.lang.RuntimeException: Unable to start activity **ComponentInfo{com.clearsoft.welivre/com.braunster.chatsdk.activities.ChatSDKLoginActivity}: de.greenrobot.dao.DaoException: Property 'entityID' is not part of com.braunster.chatsdk.dao.BUserDao@3c8aef8**
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                           at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                        Caused by: de.greenrobot.dao.DaoException: Property 'entityID' is not part of com.braunster.chatsdk.dao.BUserDao@3c8aef8
                                                                           at de.greenrobot.dao.query.WhereCollector.checkProperty(WhereCollector.java:88)
                                                                           at de.greenrobot.dao.query.WhereCollector.checkCondition(WhereCollector.java:73)
                                                                           at de.greenrobot.dao.query.WhereCollector.add(WhereCollector.java:40)
                                                                           at de.greenrobot.dao.query.QueryBuilder.where(QueryBuilder.java:99)
                                                                           at com.braunster.chatsdk.dao.core.DaoCore.fetchEntityWithProperty(DaoCore.java:103)
                                                                           at com.braunster.chatsdk.dao.core.DaoCore.fetchEntityWithEntityID(DaoCore.java:97)
                                                                           at com.braunster.androidchatsdk.firebaseplugin.firebase.BChatcatNetworkAdapter.currentUserModel(BChatcatNetworkAdapter.java:274)
                                                                           at com.braunster.androidchatsdk.firebaseplugin.firebase.BChatcatNetworkAdapter.setUserOnline(BChatcatNetworkAdapter.java:323)
                                                                           at com.braunster.chatsdk.activities.ChatSDKBaseActivity.onStart(ChatSDKBaseActivity.java:233)
                                                                           at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
                                                                           at android.app.Activity.performStart(Activity.java:6320)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2412)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                           at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5529) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by bensmiley** [comment]
For us to help you would need to provide more details. For example, are you using the default version of the SDK or have you made changes? What are the steps to reproduce the issue?

**Comment by PgVova** [comment]
I`m use default version of sdk, everything is done according to the instructions, and after login and registration i have this problem. Its roblem in DB i think, but table has property "entityID" !

**Comment by bensmiley** [comment]
Have you made any changes to the project? code or Firebase configuration? Have you tried deleting and reinstalling the app?

**Comment by PgVova** [comment]
Only by instruction, login and register work in Firebase, but after result from Firebase this trouble! Yes, i reinstall app, but this problem again! I  try builld daogenerator too, but its not help!

**Comment by jay2342** [comment]
help me for my issues
