### ISSUE TITLE
App crashes when logout is pressed

### ISSUE THREAD

**Issue by MonAdam** [chat-sdk/chat-sdk-android#128]
Following exception is thrown, when pressed on LogOut button,

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1446488 bytes
                                                                at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3805)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                             Caused by: android.os.TransactionTooLargeException: data parcel size 1446488 bytes
                                                                at android.os.BinderProxy.transactNative(Native Method)
                                                                at android.os.BinderProxy.transact(Binder.java:615)
                                                                at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3716)
                                                                at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3797)
                                                                at android.os.Handler.handleCallback(Handler.java:751) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:6165) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 

Please suggest.

**Comment by bensmiley** [comment]
In order to help with this issue we will need some more details. Can you tell me whether you have made any changes to the default SDK? Also, what are the steps to reproduce this issue?
