### ISSUE TITLE
App crashes when saving user profile

### ISSUE THREAD

**Issue by jagas** [chat-sdk/chat-sdk-android#173]
Not sure which data affects it but to reproduce

just fill the info in user profile (like phone, location, etc)
and click save.

```
  java.util.NoSuchElementException at java.util.HashMap$HashIterator.nextEntry(HashMap.java:790)
   at java.util.HashMap$KeyIterator.next(HashMap.java:815)
at co.chatsdk.ui.profile.EditProfileActivity.saveAndExit(EditProfileActivity.java:273)
  at co.chatsdk.ui.profile.EditProfileActivity.onOptionsItemSelected(EditProfileActivity.java:215)
```

**Comment by bensmiley** [comment]
Fixed in v4.0.1
