### ISSUE TITLE
Release apk gives error

### ISSUE THREAD

**Issue by abbaselectricwala** [chat-sdk/chat-sdk-android#258]
Getting the following error:

Caused by: org.a.a.d: Could not init DAOConfig
                                                     at org.a.a.d.a.<init>(DaoConfig.java:94)
                                                     at org.a.a.b.a(AbstractDaoMaster.java:44)
                                                     at co.chatsdk.a.c.d.<init>(DaoMaster.java:62)
                                                     at co.chatsdk.a.c.d.<init>(DaoMaster.java:57)
                                                     at co.chatsdk.a.c.c.a(DaoCore.java:1081)
                                                     at co.chatsdk.a.k.a.a(ChatSDK.java:2028)
                                                     at com.app.regly.view.activity.RGSplashScreenActivity.onCreate(RGSplashScreenActivity.java:91)
                                                     at android.app.Activity.performCreate(Activity.java:6847)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:163) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6342) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
                                                  Caused by: java.lang.NoSuchFieldException: TABLENAME
                                                     at java.lang.Class.getField(Class.java:1549)
                                                     at org.a.a.d.a.<init>(DaoConfig.java:56)
                                                     at org.a.a.b.a(AbstractDaoMaster.java:44) 
                                                     at co.chatsdk.a.c.d.<init>(DaoMaster.java:62) 
                                                     at co.chatsdk.a.c.d.<init>(DaoMaster.java:57) 
                                                     at co.chatsdk.a.c.c.a(DaoCore.java:1081) 
                                                     at co.chatsdk.a.k.a.a(ChatSDK.java:2028) 
                                                     at com.app.regly.view.activity.RGSplashScreenActivity.onCreate(RGSplashScreenActivity.java:91) 
                                                     at android.app.Activity.performCreate(Activity.java:6847) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:163) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6342) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 

Please help me out.

**Comment by KAPLANDROID** [comment]
`
-keep class co.chatsdk.** { *; }
`
`
-dontwarn co.chatsdk.**`

Add this to your  proguard-rules.pro file
