### ISSUE TITLE
Crashing while adding as module using path

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#263]
After cloning chat-sdk-android, I made one more project with name ChatSdkParent and imported the modules from chat-sdk-android using path and started getting  "Make sure to call FirebaseApp.initializeApp(Context) first." error.

Point to not i imported module using path refer here https://stackoverflow.com/questions/32395675/how-to-import-module-without-creating-copy-in-android-studio

troubleshooting i did:
1. Searched FirebaseApp in chat-sdk but didn't get anywhere.
2. Tried adding FirebaseApp.getInstance(context) in ChatSdkParent Application class ... didn't work same issue

FATAL EXCEPTION: main
                                                   Process: guarddoorupdate.app.com.chatsdkparent, PID: 28279
                                                   java.lang.RuntimeException: Unable to create application guarddoorupdate.app.com.chatsdkparent.MyApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process guarddoorupdate.app.com.chatsdkparent. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5973)
                                                       at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process guarddoorupdate.app.com.chatsdkparent. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                       at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
                                                       at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                       at co.chatsdk.firebase.push.FirebasePushHandler.<init>(FirebasePushHandler.java:46)
                                                       at co.chatsdk.firebase.push.FirebasePushModule.activate(FirebasePushModule.java:22)
                                                       at co.chatsdk.firebase.push.FirebasePushModule.activateForFirebase(FirebasePushModule.java:13)
                                                       at guarddoorupdate.app.com.chatsdkparent.MyApplication.onCreate(MyApplication.java:40)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
                                                       at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154)

**Comment by bensmiley** [comment]
Can you share the Chat SDK initialization code you're running in your application onCreate method?

**Comment by rahulsharmagbpec** [comment]
@Override
    public void onCreate() {
        super.onCreate();

        Context context = getApplicationContext();
        FirebaseApp.initializeApp(context);
        Configuration.Builder builder = new Configuration.Builder(context);
//        builder.firebaseRootPath("firebase_v4_web_new_4");
        builder.firebaseRootPath("18_02");

        ChatSDK.initialize(builder.build());

        UserInterfaceModule.activate(context);

        FirebaseModule.activate();

        FirebaseFileStorageModule.activate();
        FirebasePushModule.activateForFirebase();
        Log.e("TAG", "oncreate finished");
    }

**Comment by bensmiley** [comment]
I think you shouldn't call FirebaseApp.initializeApp(context). Have you added this to your Gradle file ([link](https://firebase.google.com/docs/android/setup))? 

```
// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'
```

**Comment by rahulsharmagbpec** [comment]
working fine thanks
