### ISSUE TITLE
Proguard Error when import manual libraries

### ISSUE THREAD

**Issue by eakteam** [chat-sdk/chat-sdk-android#295]
I have added in proguard rules : 

```
#CHAT SDK
-keep class co.chatsdk.core.dao.** { *; }
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
    public static java.lang.String TABLENAME;
}

-keep class **$Properties

# If you do not use SQLCipher:
-dontwarn org.greenrobot.greendao.database.**

-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.common.internal.DoNotStrip *;
}

# Keep native methods
-keepclassmembers class * {
    native <methods>;
}

-dontwarn okio.**
-dontwarn com.squareup.okhttp.**
-dontwarn okhttp3.**
-dontwarn javax.annotation.**
-dontwarn com.android.volley.toolbox.**
-dontwarn com.facebook.infer.**
#END CHAT
```

But it throws warning and cannot compile with following error : 

```
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find superclass or interface rx.Observable$OnSubscribe
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find superclass or interface rx.functions.Func0
Warning: org.greenrobot.greendao.AbstractDao: can't find referenced class rx.schedulers.Schedulers
Warning: org.greenrobot.greendao.AbstractDao: can't find referenced class rx.schedulers.Schedulers
Warning: org.greenrobot.greendao.AbstractDaoSession: can't find referenced class rx.schedulers.Schedulers
Warning: org.greenrobot.greendao.AbstractDaoSession: can't find referenced class rx.schedulers.Schedulers
Warning: org.greenrobot.greendao.query.Query: can't find referenced class rx.schedulers.Schedulers
Warning: org.greenrobot.greendao.query.Query: can't find referenced class rx.schedulers.Schedulers
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable$OnSubscribe
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.exceptions.Exceptions
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Observable$OnSubscribe
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.exceptions.Exceptions
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber
Warning: org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Observable$OnSubscribe
Warning: org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Scheduler
Warning: org.greenrobot.greendao.rx.RxUtils: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.functions.Func0
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.functions.Func0
Warning: org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable
Warning: org.joda.time.DateMidnight: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.DateTime: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.DateTimeZone: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.DateTimeZone: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.Days: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Days: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.Duration: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Hours: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Hours: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.Instant: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.LocalDate: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.LocalDate: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.LocalDateTime: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.LocalDateTime: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.LocalTime: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.LocalTime: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.Minutes: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Minutes: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.MonthDay: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.MonthDay: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.Months: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Months: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.MutableDateTime: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.MutablePeriod: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Period: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Seconds: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Seconds: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.Weeks: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Weeks: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.YearMonth: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.YearMonth: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.Years: can't find referenced class org.joda.convert.FromString
Warning: org.joda.time.Years: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.base.AbstractDateTime: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.base.AbstractDuration: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.base.AbstractInstant: can't find referenced class org.joda.convert.ToString
Warning: org.joda.time.base.AbstractPeriod: can't find referenced class org.joda.convert.ToString
```

If add to proguard rules those lines : 

```
-dontwarn org.joda.time.**
-dontwarn org.joda.time.**
-dontwarn org.greenrobot.greendao.**
```

It generate apk succesfully but after login to chat it throws this error : 

```
Fatal Exception: java.lang.AbstractMethodError: abstract method "void gzc.subscribe$43f8f32(gyy)"
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(SourceFile:40)
       at io.reactivex.Observable.subscribe(SourceFile:12051)
       at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(SourceFile:42)
       at io.reactivex.Observable.subscribe(SourceFile:12051)
       at co.chatsdk.firebase.FirebaseEventHandler.currentUserOn(SourceFile:81)
       at co.chatsdk.firebase.FirebaseEventHandler.lambda$sko2oisNmpIFmA2kzfL1Dbs-nlM(SourceFile)
       at -$$Lambda$asb$sko2oisNmpIFmA2kzfL1Dbs-nlM.trigger(lambda)
       at co.chatsdk.firebase.FirebaseEventListener.lambda$onChildAdded$0(SourceFile:71)
       at co.chatsdk.firebase.FirebaseEventListener.lambda$KG0LYGzfaVAfLy_4DntVD3PPils(SourceFile)
       at -$$Lambda$asc$KG0LYGzfaVAfLy_4DntVD3PPils.run(lambda)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:760)
```

**Comment by thecmart** [comment]
@eakteam There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue.
