### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to read from field 'co.chatsdk.core.handlers.AuthenticationHandler co.chatsdk.core.base.BaseNetworkAdapter.auth' on a null object reference

### ISSUE THREAD

**Issue by developer20atmoderni** [chat-sdk/chat-sdk-android#302]
I have integrated the audio-message chat sdk with my code, I am using this sdk for China. So I got the xmpp client from you. I have added that as Network adapter too. But now facing the above issue. 
As google products are banned in China, so I initialize the  chat sdk by following  code in Application class
`public class MyApp extends MultiDexApplication {

    @Override
    public void onCreate() {
        super.onCreate();
        Context context = getApplicationContext();

        Configuration.Builder builder = new Configuration.Builder(context);

        // Initialize the Chat SDK
        ChatSDK.initialize(builder.build());

        UserInterfaceModule.activate(context);
        //FirebaseModule.activate();
       // FirebaseFileStorageModule.activate();

    }
}
`

By commenting the Firebase code. but facing the following exception
`07-06 17:48:07.079 22248-22248/in.moderni.roompersistencedatabase E/AndroidRuntime: FATAL EXCEPTION: main
    Process: in.moderni.roompersistencedatabase, PID: 22248
    java.lang.RuntimeException: Unable to start activity ComponentInfo{in.moderni.roompersistencedatabase/co.chatsdk.ui.login.LoginActivity}: java.lang.NullPointerException: Attempt to read from field 'co.chatsdk.core.handlers.AuthenticationHandler co.chatsdk.core.base.BaseNetworkAdapter.auth' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'co.chatsdk.core.handlers.AuthenticationHandler co.chatsdk.core.base.BaseNetworkAdapter.auth' on a null object reference
        at co.chatsdk.core.session.NM.auth(NM.java:37)
        at co.chatsdk.ui.login.LoginActivity.initViews(LoginActivity.java:96)
        at co.chatsdk.ui.login.LoginActivity.onCreate(LoginActivity.java:73)
        at android.app.Activity.performCreate(Activity.java:6672)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
`

**Comment by thecmart** [comment]
@developer20atmoderni We have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.
