### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by mechaadi** [chat-sdk/chat-sdk-android#303]
whenever i try to login i get a toast "Can't pass null for argument 'pathString' in child()"

    java.lang.Exception: java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()
    W/System.err:     at co.chatsdk.core.session.ChatSDK.logError(ChatSDK.java:63)
                  at co.chatsdk.ui.login.LoginActivity.lambda$authenticateWithDetails$3$LoginActivity(LoginActivity.java:288)
                  at co.chatsdk.ui.login.LoginActivity$$Lambda$8.accept(Unknown Source)
                  at io.reactivex.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:65)
                  at io.reactivex.internal.operators.completable.CompletableDoFinally$DoFinallyObserver.onError(CompletableDoFinally.java:74)
                  at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:88)
                  at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                  at android.os.Handler.handleCallback(Handler.java:836)
                  at android.os.Handler.dispatchMessage(Handler.java:103)
                  at android.os.Looper.loop(Looper.java:203)
                  at android.app.ActivityThread.main(ActivityThread.java:6339)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
    W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
              Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()
                  at com.google.firebase.database.DatabaseReference.child(Unknown Source)
                  at co.chatsdk.firebase.FirebasePaths.firebaseRef(FirebasePaths.java:45)
                  at co.chatsdk.firebase.FirebasePaths.usersRef(FirebasePaths.java:51)
                  at co.chatsdk.firebase.FirebasePaths.userRef(FirebasePaths.java:56)
                  at co.chatsdk.firebase.wrappers.UserWrapper.ref(UserWrapper.java:316)
                  at co.chatsdk.firebase.wrappers.UserWrapper.lambda$once$1$UserWrapper(UserWrapper.java:169)
                  at co.chatsdk.firebase.wrappers.UserWrapper$$Lambda$0.subscribe(Unknown Source)
                  at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
                  at io.reactivex.Completable.subscribe(Completable.java:1664)
    W/System.err:     at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
                  at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
                  at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                  at java.lang.Thread.run(Thread.java:761)

**Comment by mechaadi** [comment]
closing this issue
