### ISSUE TITLE
Chatsdk for China using XMPP is not getting run

### ISSUE THREAD

**Issue by developer20atmoderni** [chat-sdk/chat-sdk-android#312]
We have followed [this]( https://github.com/chat-sdk/chat-sdk-android#adding-modules-manually) these instruction provided by you. then we have added the given code in `onCreate()` of `MainActivity.java`
 
```
Context context = getApplicationContext();

// Create a new configuration
        Configuration.Builder builder = new Configuration.Builder(context);

// Initialize the Chat SDK
        ChatSDK.initialize(builder.build());
        UserInterfaceModule.activate(context);
        AudioMessageModule.activate();//as we have this module so I have activated this
// [AudioMessageModule.activateForXMPP(); we have not found activateForXMPP() method]
```

But after when I run the code it gives me the null pointer exception for 
   Caused by: `java.lang.NullPointerException: Attempt to write to field 'co.chatsdk.core.handlers.AudioMessageHandler`

```
co.chatsdk.core.base.BaseNetworkAdapter.audioMessage' on a null object reference
        at co.chatsdk.message.audio.AudioMessageModule.activate(AudioMessageModule.java:13)
        at com.example.moderni.myapplication.MainActivity.onCreate(MainActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
```

Also we have not found the integration of chatsdk with XMPP. If you have a specific link or video of the same, please provide us.
We have found the open issue for it on

**Comment by bensmiley** [comment]
@developer20atmoderni in order to use the XMPP adapter you would need to purchase a license [here](http://chatsdk.co/xmpp/). When you do that you will get instructions to install the XMPP support.
