### ISSUE TITLE
App crash after login with RxJava error

### ISSUE THREAD

**Issue by sodiqOladeni** [chat-sdk/chat-sdk-android#383]
Kindly help check for the cause of the below error message, it crashes whenever i finish with the login page to proceed to the main ui.

```
10-03 04:45:37.521 25957-25957/ng.cloudware.mlchat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ng.cloudware.mlchat, PID: 25957
    io.reactivex.exceptions.UndeliverableException: java.lang.Throwable: Permission denied
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:77)
        at co.chatsdk.firebase.utils.FirebaseRX.lambda$null$2(FirebaseRX.java:38)
        at co.chatsdk.firebase.utils.-$$Lambda$FirebaseRX$Wa3M_C5KAs4giSt0dcOligvizow.onComplete(lambda)
        at com.google.android.gms.internal.firebase_database.zzdh.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.Throwable: Permission denied
        at co.chatsdk.firebase.utils.FirebaseRX.lambda$null$2(FirebaseRX.java:38) 
        at co.chatsdk.firebase.utils.-$$Lambda$FirebaseRX$Wa3M_C5KAs4giSt0dcOligvizow.onComplete(lambda) 
        at com.google.android.gms.internal.firebase_database.zzdh.run(Unknown Source) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

**Comment by sodiqOladeni** [comment]
Someone should kindly help on this @bensmiley @kykrueger

**Comment by bensmiley** [comment]
@sodiqOladeni Have you updated the security rules for your project? Maybe you could have a look at this [tutorial video](https://www.youtube.com/channel/UCQ_2hk0SOwoca0cfa5aDedA) to check that you've completed every step.

**Comment by sodiqOladeni** [comment]
@bensmiley Thanks for the support, i'm adding the rule to Cloud Firestore (Beta) instead of Realtime database, have corrected that and it's now working fine. Thanks once again

**Comment by mehtaketan7** [comment]
@bensmiley  what should I set in config.firebaseRootPath("") if I am accessing my personal realtime database?

**Comment by bensmiley** [comment]
You can put any string. In your database the data will be stored at: `/rootPath/...`
