### ISSUE TITLE
ConcurrentModificationException while creating group

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#387]
UncaughtException: io.reactivex.exceptions.UndeliverableException: java.util.ConcurrentModificationException
                                                                             at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
                                                                             at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:57)
                                                                             at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:90)
                                                                             at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                          Caused by: java.util.ConcurrentModificationException
                                                                             at java.util.ArrayList$Itr.next(ArrayList.java:831)
                                                                             at co.chatsdk.core.utils.UserListItemConverter.toUserItemList(UserListItemConverter.java:16)
                                                                             at co.chatsdk.ui.contacts.ContactsFragment.lambda$loadData$2$ContactsFragment(ContactsFragment.java:277)
                                                                             at co.chatsdk.ui.contacts.ContactsFragment$$Lambda$2.run(Unknown Source)
                                                                             at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:54)
                                                                             at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:90) 
                                                                             at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109) 
                                                                             at android.os.Handler.handleCallback(Handler.java:751) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by bensmiley** [comment]
I expect this is fixed in 4.6.0 if it persists please reopen and fill out the issue template.
