### ISSUE TITLE
Read Receipt crashing sometimes, logs are given

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#393]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.joda.time.base.AbstractInstant.isAfter(long)' on a null object reference
       at co.chatsdk.read_receipts.FirebaseReadReceiptHandler.readReceiptsEnabledForMessage(FirebaseReadReceiptHandler.java:114)
       at co.chatsdk.read_receipts.FirebaseReadReceiptHandler.setReadStatus(FirebaseReadReceiptHandler.java:169)
       at co.chatsdk.read_receipts.FirebaseReadReceiptHandler.access$000(FirebaseReadReceiptHandler.java:37)
       at co.chatsdk.read_receipts.FirebaseReadReceiptHandler$1.accept(FirebaseReadReceiptHandler.java:45)
       at co.chatsdk.read_receipts.FirebaseReadReceiptHandler$1.accept(FirebaseReadReceiptHandler.java:42)
       at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)

**Comment by bensmiley** [comment]
Fixed in 4.6.0.
