### ISSUE TITLE
frequently crash happening

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#394]
```
io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'boolean org.joda.time.base.AbstractInstant.isAfter(long)' on a null object reference
                                                          at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                          at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                          at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
                                                          at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
                                                          at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
                                                          at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
                                                          at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
                                                          at co.chatsdk.firebase.FirebaseEventHandler.lambda$null$2$FirebaseEventHandler(FirebaseEventHandler.java:83)
                                                          at co.chatsdk.firebase.FirebaseEventHandler$$Lambda$16.accept(Unknown Source)
                                                          at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:95)
                                                          at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
                                                          at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:67)
                                                          at co.chatsdk.firebase.wrappers.ThreadWrapper$2.run(ThreadWrapper.java:320)
                                                          at org.greenrobot.greendao.AbstractDaoSession.runInTx(AbstractDaoSession.java:152)
                                                          at co.chatsdk.firebase.wrappers.ThreadWrapper.lambda$null$8$ThreadWrapper(ThreadWrapper.java:281)
                                                          at co.chatsdk.firebase.wrappers.ThreadWrapper$$Lambda$29.trigger(Unknown Source)
                                                          at co.chatsdk.firebase.FirebaseEventListener.lambda$onChildAdded$0$FirebaseEventListener(FirebaseEventListener.java:71)
                                                          at co.chatsdk.firebase.FirebaseEventListener$$Lambda$0.run(Unknown Source)
                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                          at java.lang.Thread.run(Thread.java:761)
                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.joda.time.base.AbstractInstant.isAfter(long)' on a null object reference
                                                          at co.chatsdk.read_receipts.FirebaseReadReceiptHandler.readReceiptsEnabledForMessage(FirebaseReadReceiptHandler.java:114)
                                                          at co.chatsdk.read_receipts.FirebaseReadReceiptHandler.setReadStatus(FirebaseReadReceiptHandler.java:169)
                                                          at co.chatsdk.read_receipts.FirebaseReadReceiptHandler.access$000(FirebaseReadReceiptHandler.java:37)
                                                          at co.chatsdk.read_receipts.FirebaseReadReceiptHandler$1.accept(FirebaseReadReceiptHandler.java:45)
                                                          at co.chatsdk.read_receipts.FirebaseReadReceiptHandler$1.accept(FirebaseReadReceiptHandler.java:42)
```

**Comment by bensmiley** [comment]
Fixed in 4.6.0.
