### ISSUE TITLE
crash while clicking on private group name for details

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#395]
```
java.lang.NullPointerException: Attempt to read from field 'co.chatsdk.core.handlers.ContactHandler co.chatsdk.core.base.BaseNetworkAdapter.contact' on a null object reference
                                                                           at co.chatsdk.core.session.NM.contact(NM.java:69)
                                                                           at co.chatsdk.ui.main.MainActivity.requestReadContacts(MainActivity.java:107)
                                                                           at co.chatsdk.ui.main.MainActivity.lambda$onCreate$1$MainActivity(MainActivity.java:64)
                                                                           at co.chatsdk.ui.main.MainActivity$$Lambda$0.run(Unknown Source:2)
                                                                           at io.reactivex.internal.operators.completable.CompletableDoFinally$DoFinallyObserver.runFinally(CompletableDoFinally.java:98)
                                                                           at io.reactivex.internal.operators.completable.CompletableDoFinally$DoFinallyObserver.onComplete(CompletableDoFinally.java:81)
                                                                           at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:116)
                                                                           at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:116)
                                                                           at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
                                                                           at co.chatsdk.core.utils.PermissionRequestHandler.lambda$requestPermission$0$PermissionRequestHandler(PermissionRequestHandler.java:87)
                                                                           at co.chatsdk.core.utils.PermissionRequestHandler$$Lambda$0.subscribe(Unknown Source:8)
                                                                           at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
                                                                           at io.reactivex.Completable.subscribe(Completable.java:1918)
                                                                           at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
                                                                           at io.reactivex.Completable.subscribe(Completable.java:1918)
                                                                           at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
                                                                           at io.reactivex.Completable.subscribe(Completable.java:1918)
                                                                           at io.reactivex.internal.operators.completable.CompletableDoFinally.subscribeActual(CompletableDoFinally.java:45)
                                                                           at io.reactivex.Completable.subscribe(Completable.java:1918)
                                                                           at co.chatsdk.ui.main.MainActivity.requestPermissionSafely(MainActivity.java:82)
                                                                           at co.chatsdk.ui.main.MainActivity.onCreate(MainActivity.java:64)
                                                                           at com.app.myactivity.activities.ChatMainActivity.onCreate(ChatMainActivity.java:58)
                                                                           at android.app.Activity.performCreate(Activity.java:7036)
                                                                           at android.app.Activity.performCreate(Activity.java:7027)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6501)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by bensmiley** [comment]
I think this is caused by not having initialized the Chat SDK. The Chat SDK must be initialized before any activity starts. See this [guide](https://github.com/chat-sdk/chat-sdk-android#initializing-the-chat-sdk). And these [video tutorials](https://www.youtube.com/channel/UCQ_2hk0SOwoca0cfa5aDedA).

**Comment by rahulsharmagbpec** [comment]
No, this crash is cause of image used in thread-detail, error is recycle() image cannot be used and its going back to previous activity and there above logs are coming, for now i commented the image showing part. but issues is not solved

**Comment by bensmiley** [comment]
@rahulsharmagbpec could you tell me which version of the Chat SDK you're using? Also, give me some steps to reproduce the issue? In general, it's very hard for me to fix an issue where only a stack trace is provided. Please see the [issue template](https://github.com/chat-sdk/chat-sdk-android/blob/master/Issue%20Template.md).
