### ISSUE TITLE
Failing to send image message using chatSDK UI

### ISSUE THREAD

**Issue by MuhammedRefaat** [chat-sdk/chat-sdk-android#488]
1. **Is the bug present in the demo Chat SDK project?**
No
2. **What modifications have you made to the Chat SDK?**
Nothing, It's not in the demo app, in the demo app it's workig perfectly
3. **Android Version:**
8.0.0
4. **Steps taken to reproduce the problem:**
Implementing ChatSDK in my project and trying to use it to send an image using ChatSDK UI chat screen.
5. **Expected result:**
to send the image successfully
6. **Actual result:**
The image is not being sent with image dsiplayed
![error_sending_image](https://user-images.githubusercontent.com/4974603/53387664-5039e480-39a1-11e9-962e-c848d4cfd942.png)

7. **Comments:**

As obvious in the screenshot attached, when trying to send an image using ChatSDK UI chat screen, I'm getting the displayed error 

> Attempt to invoke interface
> method 'io.reactivex.Observable
> co.chatsdk.core.nandlers.UploadHandler.upl
> oadlmage(android.graphics.Bitmap)' on a
> null object reference

Despite I'm making the required installations while initializing the chatSDK as following:

```
        // Initialize the Chat SDK
        try {
            ChatSDK.initialize(builder.build(), new FirebaseNetworkAdapter(), new BaseInterfaceAdapter(context));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // File storage is needed for profile image upload and image messages
        FirebaseFileStorageModule.activate();
        FirebaseModule.activate();
        FirebasePushModule.activate();
        UserInterfaceModule.activate(MainActivity.this);
        AppBackgroundMonitor.shared().setEnabled(true);
```

And That's how I start the ChatSDK chatting Activity screen:

`ChatSDK.ui().startChatActivityForID(getActivity().getApplicationContext(), thread.getEntityID());`

And the following is the log I'm getting:

```
2019-02-26 08:48:29.347 14275-14275/ae.netaq.schoolvoice W/System.err: java.lang.Exception: java.lang.NullPointerException: Attempt to invoke interface method 'io.reactivex.Observable co.chatsdk.core.handlers.UploadHandler.uploadImage(android.graphics.Bitmap)' on a null object reference
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at co.chatsdk.core.session.ChatSDK.logError(ChatSDK.java:181)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at co.chatsdk.ui.chat.ChatActivity$2.onError(ChatActivity.java:320)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6940)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
2019-02-26 08:48:29.348 14275-14275/ae.netaq.schoolvoice W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2019-02-26 08:48:29.350 14275-14275/ae.netaq.schoolvoice W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'io.reactivex.Observable co.chatsdk.core.handlers.UploadHandler.uploadImage(android.graphics.Bitmap)' on a null object reference
2019-02-26 08:48:29.350 14275-14275/ae.netaq.schoolvoice W/System.err:     at co.chatsdk.core.base.BaseImageMessageHandler.lambda$sendMessageWithImage$0(BaseImageMessageHandler.java:58)
2019-02-26 08:48:29.350 14275-14275/ae.netaq.schoolvoice W/System.err:     at co.chatsdk.core.base.-$$Lambda$BaseImageMessageHandler$WcOMA63FHZRrFiusqV8RKjJmm6o.subscribe(Unknown Source:6)
2019-02-26 08:48:29.350 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
2019-02-26 08:48:29.350 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12090)
2019-02-26 08:48:29.351 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2019-02-26 08:48:29.351 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
2019-02-26 08:48:29.351 14275-14275/ae.netaq.schoolvoice W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
2019-02-26 08:48:29.351 14275-14275/ae.netaq.schoolvoice W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-02-26 08:48:29.351 14275-14275/ae.netaq.schoolvoice W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-02-26 08:48:29.351 14275-14275/ae.netaq.schoolvoice W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-02-26 08:48:29.351 14275-14275/ae.netaq.schoolvoice W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-02-26 08:48:29.351 14275-14275/ae.netaq.schoolvoice W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by bensmiley** [comment]
The upload handler is null. I expect it's caused by this line:

```
UserInterfaceModule.activate(MainActivity.this);
```

Can you try calling this line before you activate the modules?

**Comment by MuhammedRefaat** [comment]
Tried that, unfortunately still the same with same error logs

**Comment by deeppudasaini** [comment]
OK

**Comment by MuhammedRefaat** [comment]
Solved, 
Actually the cause was because of the order of the activation commands, but not only because of `UserInterfaceModule`, it was because of `FirebaseFileStorageModule` is being activated using `BaseNetworkAdapter` of `NetworkManager `which is being re-instantiated by `FirebaseModule.activate()`, so activating `FirebaseModule` after activating `FirebaseFileStorageModule` was nullifying the `UploadHandler` referenced by `FirebaseFileStorageModule`. 

For reference, the code of  `FirebaseFileStorageModule.Activate()` is:
```
public class FirebaseFileStorageModule {
    public static void activate () {
        NetworkManager.shared().a.upload = new FirebaseUploadHandler();
    }
}
```

and the code of  `FirebaseModule.Activate()` is:
```
public class FirebaseModule {
    public static void activate() {
        NetworkManager.shared().a = new FirebaseNetworkAdapter();
    }
}
```

Therefor, at the end, I had to rearrange the activations to be like the following:

```
UserInterfaceModule.activate(MainActivity.this);
FirebaseModule.activate();
FirebasePushModule.activate();
FirebaseFileStorageModule.activate();
```
