### ISSUE TITLE
Sending two image messages quickly causes crash

### ISSUE THREAD

**Issue by kykrueger** [chat-sdk/chat-sdk-android#51]
The SuperToast service is crashing the app if two image messages are sent quickly. 
The crash happens in `ChatSDKUiHelper.showProgressCard(String text)` at the bolded line shown below. 

<pre>

    public void showProgressCard(String text){

        if (colleted())
            return;

        if (context.get() instanceof Activity) {

            initCardToast();

            View decorView = ((Activity) context.get()).getWindow().getDecorView().findViewById(android.R.id.content);
            ViewGroup viewGroup = superCardToastProgress.getViewGroup();

            if (viewGroup!=null && superCardToastProgress.getView()!= null && viewGroup.findViewById(superCardToastProgress.getView().getId()) != null)
                viewGroup.removeView(superCardToastProgress.getView());

            decorView.findViewById(R.id.card_container).bringToFront();

            superCardToastProgress.setText(text);

            if (!superCardToastProgress.isShowing())
               <b> superCardToastProgress.show(); </b>

        }
    }
</pre>

The stack trace is the following 
```
                                                                                  --------- beginning of crash
03-24 17:51:56.147 12215-12215/com.braunster.androidchatsdk.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.braunster.androidchatsdk.app, PID: 12215
                                                                                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6809, result=-1, data=Intent { (has extras) }} to activity {com.braunster.androidchatsdk.app/com.braunster.chatsdk.activities.ChatSDKChatActivity}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
                                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
                                                                                      at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                   Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                                      at android.view.ViewGroup.addView(ViewGroup.java:4189)
                                                                                      at android.view.ViewGroup.addView(ViewGroup.java:4171)
                                                                                      at com.github.johnpersano.supertoasts.SuperCardToast.show(SuperCardToast.java:348)
                                                                                      at com.braunster.chatsdk.Utils.helper.ChatSDKUiHelper.showProgressCard(ChatSDKUiHelper.java:388)
                                                                                      at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.sendingMessageToast(ChatSDKChatHelper.java:486)
                                                                                      at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.sendImageMessage(ChatSDKChatHelper.java:641)
                                                                                      at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.processCroppedPhoto(ChatSDKChatHelper.java:420)
                                                                                      at com.braunster.chatsdk.Utils.helper.ChatSDKChatHelper.handleResult(ChatSDKChatHelper.java:373)
                                                                                      at com.braunster.chatsdk.activities.abstracted.ChatSDKAbstractChatActivity.onActivityResult(ChatSDKAbstractChatActivity.java:566)
                                                                                      at android.app.Activity.dispatchActivityResult(Activity.java:6932)
                                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
                                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
                                                                                      at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

The toast should not be launching if it is already displayed, and I need to check how this problem is occurring despite us checking if the toast is filled or not.

**Comment by kykrueger** [comment]
This issue was found while trying to reproduce #47 .
