### ISSUE TITLE
Problem with Push Notifications

### ISSUE THREAD

**Issue by wazowski78** [chat-sdk/chat-sdk-android#53]
Hi,

I have follow the tutorial, and now I have some doubts with the Push Notifications set up. I have added the Backendless keys, and Push notifications works from iOS to Android, but from Android to iOS are not working at all.

I am working with debug version, so I am thinking the problem may be because it. I have read this in the manual:

> All the code for Push Notifications is already included in the Chat SDK. Getting them working only requires a small amount of configuration. For help regarding this, you can take a look at the Backendless guide.
NOTE:
Some of the steps in this tutorial include adding code to the app, these steps should be unnecessary as they have already been added to the project.
NOTE:
If you want push notifications to work in Development mode make sure to configure them in your provisioning profile for both development and production.
>
What are the steps that are not necessary, and the other question, what do I have to configure Android for development?

**Comment by kykrueger** [comment]
Hi,

The main difference between development and production with our configuration of the SDK is debug vs release mode. There are no differences in our development mode that I know of which should cause problems with push notifications. If there was indeed a problem related to these profiles, I would not any push notifications to appear. 

For that reason I think this note may have been carried over from the iOS documentation accidentally. 

Could you let me know if the iOS to iOS and Android to Android notifications are working?

**Comment by wazowski78** [comment]
Hi,

I have seen that in the /app/build.gradle exists this both configurations:

```signingConfigs {

        /*debug {
            storeFile file('/media/braunster/Code/Android/braunserkey')
            keyAlias 'braunsteralias'
            keyPassword 'Itzikbraun1991'
            storePassword 'Itzikbraun1991'
        }*/

        release {
            storeFile file('/media/braunster/Code/Android/braunserkey')
            keyAlias 'braunsteralias'
            keyPassword 'Itzikbraun1991'
            storePassword 'Itzikbraun1991'
        }
    }```

You can see that development config is commented, so I have a doubt about change the commented configuration. At this moment I get an error about the release signing.

iOS to iOS are working fine, iOS to Android as well, but Android to iOS are not working. I have changed several options for Firebase Server Key, but I have no good result.

**Comment by wazowski78** [comment]
Hi again,

I have tried several times to configure the Push Notifications for Android app, and now, I am getting this error:

```
03-28 11:24:29.738 13954-13954/com.braunster.androidchatsdk.app E/BackendlessBroadcastReceiver: Error processing push notification
                                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                                    at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
                                                                                                    at org.json.JSONTokener.nextValue(JSONTokener.java:94)
                                                                                                    at org.json.JSONObject.<init>(JSONObject.java:156)
                                                                                                    at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                                                    at com.braunster.androidchatsdk.firebaseplugin.firebase.backendless.ChatSDKReceiver.onMessage(ChatSDKReceiver.java:68)
                                                                                                    at com.backendless.push.BackendlessBroadcastReceiver.handleMessage(BackendlessBroadcastReceiver.java:198)
                                                                                                    at com.backendless.push.BackendlessBroadcastReceiver.handleIntent(BackendlessBroadcastReceiver.java:161)
                                                                                                    at com.backendless.push.BackendlessBroadcastReceiver.onReceive(BackendlessBroadcastReceiver.java:128)
                                                                                                    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2743)
                                                                                                    at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
03-28 11:24:29.755 13954-13954/com.braunster.androidchatsdk.app E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
03-28 11:24:29.756 13954-13954/com.braunster.androidchatsdk.app E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
```

**Comment by wazowski78** [comment]
And this is the error log when a test notification is sent from Backendless console:

```
03-28 11:43:39.079 13954-13954/com.braunster.androidchatsdk.app E/ChatSDKReceiver: JSONException: Value android-ticker-text of type java.lang.String cannot be converted to JSONObject
03-28 11:43:39.083 13954-13954/com.braunster.androidchatsdk.app E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
03-28 11:43:39.086 13954-13954/com.braunster.androidchatsdk.app E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
```

**Comment by wazowski78** [comment]
Today Push Notifications tests have ended with the following result with real devices:

iOS to iOS: OK
iOS to Android: OK
Android to iOS: ERROR
Android to Android: Not Tested (I do not have two Android devices)
Backendless Console to Android : ERROR ( See previous post -1)
Firebase Console to Android: ERROR (See previous post -2)

I think that it is possible that development and release certificates are bugging one each other, so if I can not make this work properly I will need to wait until release.

I really need help :)

**Comment by testsoft145** [comment]
Hi,
I have tried several times to configure the Push Notifications for Android app, and now, I am getting this error when I send a notification from Accengage server. and also my application is crashed.

 compile 'com.ad4screen.sdk:A4SSDK:3.5.+;

Error : Unable to create service com.ad4screen.sdk.service.ActivityLifecycleListenerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.toUri(int)' on a null object reference
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2771)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.toUri(int)' on a null object reference
                                                       at com.ad4screen.sdk.common.i.c(SourceFile:429)
                                                       at com.ad4screen.sdk.service.ActivityLifecycleListenerService.onCreate(SourceFile:32)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2761)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

I really need help :)

Thanks for your positive replay

**Comment by wazowski78** [comment]
Closed why? Is there any link to the solution?

**Comment by bensmiley** [comment]
We have stopped supporting Backendless and released a new version of the app which uses Firebase cloud messaging. I would recommend upgrading to that. To use Firebase with the current version you should see [this guide](https://github.com/chat-sdk/chat-sdk-android/wiki/Supporting-Firebase-push-notifications-with-v3-of-the-project).

**Comment by wazowski78** [comment]
Nice, and all the packages I have purchased previously are fully supported in this new version?

**Comment by bensmiley** [comment]
Currently the only module that's not supported is location based chat. That will be added in the next few weeks. I'll be making the other modules available tomorrow.

**Comment by wazowski78** [comment]
So I will be able to download them directly like an update or I will need to ask you for them?

**Comment by bensmiley** [comment]
They should be available in an update. If not, I can send them directly.
