### ISSUE TITLE
app crashing when opening splash activty

### ISSUE THREAD

**Issue by troubleshoooter** [chat-sdk/chat-sdk-android#537]
1. **Is the bug present in the demo Chat SDK project?**
yes, as I am implementing as the guide says
2. **What modifications have you made to the Chat SDK?**
none
3. **Android Version:**
9.0
4. **Steps taken to reproduce the problem:**
I can't as it's the SDK error
5. **Expected result:**
should open the splash screen activity
6. **Actual result:**
crashing.
7. **Comments:**

STACKTRACE::--

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dowould.dowould/co.chatsdk.ui.login.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3088)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6744)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
        at co.chatsdk.ui.main.BaseActivity.setupTouchUIToDismissKeyboard(BaseActivity.java:176)
        at co.chatsdk.ui.main.BaseActivity.setupTouchUIToDismissKeyboard(BaseActivity.java:162)
        at co.chatsdk.ui.login.LoginActivity.onCreate(LoginActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3088) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6744) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by thecmart** [comment]
Hello @ideepeshtiwari I am currently trying to reproduce this error. Please tell me which demo version are you using? We are currently updating it. Does this happen when you clone the main chatsdk project and try to run it?

**Comment by maironsoft** [comment]
Hi. I have the same issue. Is there any solution? Thanks!

**Comment by bensmiley** [comment]
Hi @maironsoft are you using the latest version of the project? If so, can you post your exact error?

**Comment by maironsoft** [comment]
Hi @bensmiley. I am using the version 4.8.9. The error is the following:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cannatrac.app, PID: 32017
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cannatrac.app/co.chatsdk.ui.login.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3131)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3270)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:220)
        at android.app.ActivityThread.main(ActivityThread.java:6939)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
        at co.chatsdk.ui.main.BaseActivity.setupTouchUIToDismissKeyboard(BaseActivity.java:176)
        at co.chatsdk.ui.main.BaseActivity.setupTouchUIToDismissKeyboard(BaseActivity.java:162)
        at co.chatsdk.ui.login.LoginActivity.onCreate(LoginActivity.java:72)
        at android.app.Activity.performCreate(Activity.java:7148)
        at android.app.Activity.performCreate(Activity.java:7139)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3111)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3270) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:220) 
        at android.app.ActivityThread.main(ActivityThread.java:6939).

I followed the documentation step by step.

Thanks for your help!

**Comment by bensmiley** [comment]
@maironsoft could you also share the code you use to setup the Chat SDK?

**Comment by maironsoft** [comment]
ok. In build.gradle project I have:

```
allprojects {
repositories {
    maven { url "http://dl.bintray.com/chat-sdk/chat-sdk-android" }
    maven { url "https://maven.google.com" }
    maven { url "https://jitpack.io" }
}
}
```

in my build.gradle app:

```
    //ChatSDK
    implementation 'co.chatsdk.chatsdk:chat-sdk-core:4.8.9'
    implementation 'co.chatsdk.chatsdk:chat-sdk-ui:4.8.9'
    implementation 'co.chatsdk.chatsdk:chat-sdk-firebase-adapter:4.8.9'
    implementation 'co.chatsdk.chatsdk:chat-sdk-firebase-file-storage:4.8.9'
```
In my MainActivity:

```
public void launchChatSDK(){
        Context context = getApplicationContext();

        try {
            // Create a new configuration
            Configuration.Builder builder = new Configuration.Builder();

            // Perform any other configuration steps (optional)
            builder.firebaseRootPath("prod");

            // Initialize the Chat SDK
            ChatSDK.initialize(context, builder.build(), FirebaseNetworkAdapter.class, BaseInterfaceAdapter.class);

            // File storage is needed for profile image upload and image messages
            FirebaseFileStorageModule.activate();

            // Push notification module
            FirebasePushModule.activate();

            // Activate any other modules you need.
            // ...

        } catch (Exception e) {
            // Handle any exceptions
            e.printStackTrace();
        }
    }

 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_loading);
        ButterKnife.bind(this);
        launchChatSDK();
    }
```

In another activity, where I launch the chat:

`ChatSDK.ui().startSplashScreenActivity(getApplicationContext());`

The error is the following in a file of the SDK (attach image):
![image](https://user-images.githubusercontent.com/17838462/72823812-44eb4980-3c42-11ea-8a92-1e7dde24b68c.png)

I setup the project firebase and respective application in firebase console. I hav another project with the same configurations, and in this the sdk work.

Thanks

**Comment by maironsoft** [comment]
@bensmiley I'm sorry. I attached the image incorrect.

![image](https://user-images.githubusercontent.com/17838462/72824349-1a4dc080-3c43-11ea-953b-6dd416406ebe.png)

**Comment by bensmiley** [comment]
@maironsoft as [per the instructions](https://github.com/chat-sdk/chat-sdk-android#initializing-the-chat-sdk), you need to have the ChatSDK.initialize code in your main Application subclass:

So you will have a class:

```
class MyApp extends Application 
```

Setup the Chat SDK in the `onCreate` method. 

Many thanks
