### ISSUE TITLE
App Crashes when denying permission

### ISSUE THREAD

**Issue by abdullahalshafi** [chat-sdk/chat-sdk-android#543]
1. **Is the bug present in the demo Chat SDK project?**
Yes

2. **What modifications have you made to the Chat SDK?**
None

3. **Android Version:**
6.0

4. **Steps taken to reproduce the problem:**
Open any thread and try to take/choose photo and deny the permission and press cancel.

5. **Expected result:**
Display error message.

6. **Actual result:**
App crashes.

7. **Comments:**
Here is the log:
```
Process: co.chatsdk.android.app, PID: 12964
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.Throwable: Grant permission to allow images to be saved to your phone permission not granted. Please enable this permission in your phone's settings.
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:77)
        at co.chatsdk.core.utils.PermissionRequestHandler.lambda$null$1$PermissionRequestHandler(PermissionRequestHandler.java:154)
        at co.chatsdk.core.utils.-$$Lambda$PermissionRequestHandler$13FTvw_p710-mh5eGzhhyi7XkCA.onClick(lambda)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.Throwable: Grant permission to allow images to be saved to your phone permission not granted. Please enable this permission in your phone's settings.
        at co.chatsdk.core.utils.PermissionRequestHandler.lambda$null$1$PermissionRequestHandler(PermissionRequestHandler.java:154) 
        at co.chatsdk.core.utils.-$$Lambda$PermissionRequestHandler$13FTvw_p710-mh5eGzhhyi7XkCA.onClick(lambda) 
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by thecmart** [comment]
@abdullahalshafi hello, we have reproduced the error and we are currently working on a solution. We will get back to you soon.

**Comment by uszkaisandor** [comment]
@thecmart 
Is there any solution for this bug?

**Comment by abdullahalshafi** [comment]
By Adding this into your Application class onCreate method will prevent the app from crashing.

 RxJavaPlugins.setErrorHandler(throwable -> {
            Log.e(TAG, "error-> " + throwable);
        });

**Comment by uszkaisandor** [comment]
@abdullahalshafi
Your solution solves the crash, but if I deny the permission multiple times, it shows a toast with an ugly text, and can't request the camera permission again only after app restart. Did you find a solution to this too?
