### ISSUE TITLE
Push notifications for chat showing error

### ISSUE THREAD

**Issue by zaidzak9** [chat-sdk/chat-sdk-android#547]
Hi i get the following error when trying to test push notifications for chat. plz help me out ... i followed the tutorial given.

```
07-02 10:39:14.380 10711-10711/ E/UncaughtException: java.lang.AbstractMethodError: abstract method "java.util.HashMap co.chatsdk.core.handlers.PushHandler.pushDataForMessage(co.chatsdk.core.dao.Message)"
        at co.chatsdk.firebase.FirebaseThreadHandler.pushForMessage(FirebaseThreadHandler.java:257)
        at co.chatsdk.firebase.FirebaseThreadHandler$1.subscribeActual(FirebaseThreadHandler.java:139)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onComplete(CompletableAndThenCompletable.java:99)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at co.chatsdk.firebase.wrappers.ThreadWrapper.lambda$pushLastMessage$25(ThreadWrapper.java:533)
        at co.chatsdk.firebase.wrappers.-$$Lambda$ThreadWrapper$HkvLi2iVZxDe_-GSS78exrxe6Fo.onComplete(lambda)
        at com.google.firebase.database.core.Repo$6.run(com.google.firebase:firebase-database@@17.0.0:404)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by sosmita4** [comment]
do you get any solution for this? I am getting the same error

**Comment by bensmiley** [comment]
When do you actually get this issue? Can you give me steps to reproduce it?

**Comment by sosmita4** [comment]
When I am creating private thread and calling  ChatSDK.ui().startChatActivityForID(context, thread.getEntityID()); in subscribe

**Comment by bensmiley** [comment]
Which version of the framework are you using?

**Comment by sosmita4** [comment]
4.8.4

**Comment by bensmiley** [comment]
Are you calling this method after the the users have authenticated? If so, can you show me where you are adding this code? Also, do both of the users exist?

**Comment by bensmiley** [comment]
Also, the original stack trace is being triggered by a message send but you don't show that in your code. Are you sure it's the same error?

**Comment by sosmita4** [comment]
I have not added any custom authentication. I am using chat sdk's default login.

Also, I am using the following code to add the user in the contact. please let me know if I am wrong anywhere.

`    UserWrapper wrapper = UserWrapper.initWithEntityId("123456");
        wrapper.metaOn();
        wrapper.onlineOn();
        User user = wrapper.getModel();


        ChatSDK.contact().addContact(user, ConnectionType.Contact).subscribe();
        List<User> users = ChatSDK.contact().contacts();//fetching contacts
        users.add(ChatSDK.currentUser());

        ChatSDK.thread().createThread(users)
                .observeOn(AndroidSchedulers.mainThread())
                .doOnError(error -> System.err.println("The error message is: " + error.getMessage()))
                .subscribe((Consumer<Thread>) thread -> {
                    try {
                        String entityID1 = thread.getEntityID();
                         ChatSDK.ui().startChatActivityForID(context, thread.getEntityID());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }, toastOnErrorConsumer());`

**Comment by sosmita4** [comment]
As you said I have tested for two different users made authenticated the used then made contact but when I sent the message I got following error

` Process: com.genext.chatapplication, PID: 21813
    java.lang.AbstractMethodError: abstract method "java.util.HashMap co.chatsdk.core.handlers.PushHandler.pushDataForMessage(co.chatsdk.core.dao.Message)"
        at co.chatsdk.firebase.FirebaseThreadHandler.pushForMessage(FirebaseThreadHandler.java:271)
        at co.chatsdk.firebase.FirebaseThreadHandler$1.subscribeActual(FirebaseThreadHandler.java:153)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onComplete(CompletableAndThenCompletable.java:99)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at co.chatsdk.firebase.wrappers.ThreadWrapper.lambda$pushLastMessage$25(ThreadWrapper.java:533)
        at co.chatsdk.firebase.wrappers.-$$Lambda$ThreadWrapper$HkvLi2iVZxDe_-GSS78exrxe6Fo.onComplete(lambda)
        at com.google.firebase.database.core.Repo$6.run(com.google.firebase:firebase-database@@19.1.0:404)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`
