### ISSUE TITLE
Error while sharing location

### ISSUE THREAD

**Issue by kanaksony** [chat-sdk/chat-sdk-android#555]
1. **Is the bug present in the demo Chat SDK project?**
Yes

2. **What modifications have you made to the Chat SDK?**
Nothing

3. **Android Version:**
9.0

4. **Steps taken to reproduce the problem:**

- Started a chat thread, 
- Click on "+" button
- Select "Location" from Actions.

5. **Expected result:**
Location Screen should opens and allow to share the location object.

6. **Actual result:**
Location Screen opens and immediately closes.

7. **Comments:**
Here is the error log - 
java.lang.Exception: java.lang.Exception: Error picking location
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.core.session.ChatSDK.logError(ChatSDK.java:121)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.ChatActivity$3.accept(ChatActivity.java:352)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.ChatActivity$3.accept(ChatActivity.java:349)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:88)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:87)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6863)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err: Caused by: java.lang.Exception: Error picking location
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.LocationSelector.handleResult(LocationSelector.java:75)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.LocationSelector.lambda$startActivityForResult$1$LocationSelector(LocationSelector.java:53)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.-$$Lambda$LocationSelector$m1mNXy7_esAoQNAarE8hzZ70Uwg.accept(Unknown Source:6)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
2019-07-18 16:06:14.905 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.main.BaseActivity.onActivityResult(BaseActivity.java:287)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.ChatActivity.onActivityResult(ChatActivity.java:589)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:7476)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4489)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4538)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-07-18 16:06:14.906 27045-27045/com.yamexchange W/System.err: 	... 5 more
2019-07-18 16:06:14.921 27045-27045/com.yamexchange W/System.err: java.lang.Exception: java.lang.Exception: Error picking location
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.core.session.ChatSDK.logError(ChatSDK.java:121)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.core.utils.CrashReporter.onError(CrashReporter.java:34)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.core.utils.CrashReportingCompletableObserver.onError(CrashReportingCompletableObserver.java:31)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:87)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6863)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
2019-07-18 16:06:14.922 27045-27045/com.yamexchange W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-07-18 16:06:14.923 27045-27045/com.yamexchange W/System.err: Caused by: java.lang.Exception: Error picking location
2019-07-18 16:06:14.923 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.LocationSelector.handleResult(LocationSelector.java:75)
2019-07-18 16:06:14.923 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.LocationSelector.lambda$startActivityForResult$1$LocationSelector(LocationSelector.java:53)
2019-07-18 16:06:14.923 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.-$$Lambda$LocationSelector$m1mNXy7_esAoQNAarE8hzZ70Uwg.accept(Unknown Source:6)
2019-07-18 16:06:14.923 27045-27045/com.yamexchange W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
2019-07-18 16:06:14.923 27045-27045/com.yamexchange W/System.err:     at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.main.BaseActivity.onActivityResult(BaseActivity.java:287)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at co.chatsdk.ui.chat.ChatActivity.onActivityResult(ChatActivity.java:589)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:7476)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4489)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4538)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-07-18 16:06:14.926 27045-27045/com.yamexchange W/System.err: 	... 5 more

NOTE: Location was enabled on my phone and also it had internet connectivity.

Thanks,
Kanak

**Comment by aymenhs** [comment]
hello,can you put all the exception, and use the format CODE here? it's not at all visible ;)
