### ISSUE TITLE
push using firebase: index.js script error,detected and resolved

### ISSUE THREAD

**Issue by aymenhs** [chat-sdk/chat-sdk-android#610]
1. **Is the bug present in the demo Chat SDK project?**
yes

2. **What modifications have you made to the Chat SDK?**
index.js modified
3. **Android Version:**
8 , 9 and 10
4. **Steps taken to reproduce the problem:**
I integrated the chat into my project since 2 years, when I wanted to use the push functionalities (which worked before 1 year ago in 2019), I got Firebase internal error :s

5. **Expected result:**
Push notification script on firebase should work ( pushToChannels) and send the push to the receiver

6. **Actual result:**
```
pushToChannels
Unhandled error { Error: data must be a non-null object
    at FirebaseMessagingError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseMessagingError (/srv/node_modules/firebase-admin/lib/utils/error.js:254:16)
    at validateStringMap (/srv/node_modules/firebase-admin/lib/messaging/messaging-types.js:67:15)
    at Object.validateMessage (/srv/node_modules/firebase-admin/lib/messaging/messaging-types.js:48:5)
    at Messaging.send (/srv/node_modules/firebase-admin/lib/messaging/messaging.js:208:27)
    at exports.pushToChannels.functions.https.onCall (/srv/index.js:231:31)
    at func (/srv/node_modules/firebase-functions/lib/providers/https.js:267:32)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  errorInfo: 
   { code: 'messaging/invalid-payload',
     message: 'data must be a non-null object' },
  codePrefix: 'messaging' }
```

7. **Comments:**
I resolved the issue by replacing within the script index.js the line 231:
> let message = buildMessage(userName, body, action, sound, type, senderId, threadId, uid);
by 
> let message = buildMessagePushMessage(userName, body, action, sound,data.type, senderId, threadId, uid);

already the buildMessage funciton accepts only 6 parameter and not 8 as the actual call to it is trying to do.

Thank you to validate that my solution is the best one :)

**Comment by bensmiley** [comment]
This should be fixed.
