### ISSUE TITLE
help with starting chatActivityForID

### ISSUE THREAD

**Issue by rikongha** [chat-sdk/chat-sdk-android#611]
I was able to get Mainactivity to startup but for my use case, I only need to have the chat screen (I'll be communicating with just one bot). Trying to start  ChatSDK.ui().startChatActivityForID(context, threadEntityId) fails and returns this error

  ```
 Process: com.iemobile, PID: 17814
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.iemobile/co.chatsdk.ui.chat.ChatActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void co.chatsdk.ui.chat.TextInputView.setDelegate(co.chatsdk.ui.chat.TextInputDelegate)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3447)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void co.chatsdk.ui.chat.TextInputView.setDelegate(co.chatsdk.ui.chat.TextInputDelegate)' on a null object reference
        at co.chatsdk.ui.chat.ChatActivity.initViews(ChatActivity.java:300)
```

**Comment by bensmiley** [comment]
@rikongha, can you show me the code you are using to set up the Chat SDK? In your main application method?

**Comment by rikongha** [comment]
@bensmiley thanks for reaching out

here's what I have on there

   try {
            val config = Configuration.Builder()
            config.facebookLoginEnabled(false)
            config.twitterLoginEnabled(false)
            config.anonymousLoginEnabled(true)
            ChatSDK.initialize(
                context,
                config.build(),
                FirebaseNetworkAdapter::class.java,
                BaseInterfaceAdapter::class.java
            )
        } catch (e: ChatSDKException) {
            Log.e("ChatSDK", e.localizedMessage)
        }

**Comment by RahatSaqib** [comment]
is this resolved? I have the same issue.

**Comment by RahatSaqib** [comment]
have you solved this error @rikongha ? I have the same error

**Comment by rikongha** [comment]
@RahatSaqib no, unfortunately, I just had to go with a custom implementation of my own

**Comment by bensmiley** [comment]
These issues seem to be related to Gradle. The way to fix it is:

1. Make sure that your library versions match Chat SDK library versions. You can do this by adding the library versions to the `ext` block in your project level build.gradle file. This ensures that you are always using a consistent version of libraries across the whole project. i.e.

Project level:

```
ext {
    greenDaoVersion = "3.2.2"
}
```

App level:

```
implementation "org.greenrobot:greendao:$greenDaoVersion"
```

2. Make a copy of your project and in that copy, delete all the custom source code you have. Then comment out half of your Gradle dependencies. Check to see if the project works. If it does, uncomment half of the remaining dependencies etc... to isolate which dependency is causing the trouble. 

If you post the problem dependency I can help to figure out why it's causing the issue.
