### ISSUE TITLE
App is crashing on creating a private thread of more than two users.

### ISSUE THREAD

**Issue by bjs007** [chat-sdk/chat-sdk-android#612]
1. **Is the bug present in the demo Chat SDK project?**
Yes. I am just following manual to install ChatSDK present here 
https://github.com/thecmart/manuals/tree/master/Tutorials
2. **What modifications have you made to the Chat SDK?**
None
3. **Android Version:**
9.0
4. **Steps taken to reproduce the problem:**
    1. Created three virtual devices on Android sdk. 
    2. Created three users in the firebase database in the real-time database.
    3. First created a group of two users in one of the devices then tried to add another user.
5. **Expected result:**
There should be a group of three users created. The Realtime database on firebase should show threads.
6. **Actual result:**
The realtime database has a thread with all the users. However, apps on all devices are crashing.
7. **Comments:**
```
2020-04-05 03:31:31.712 5161-5204/com.example.testapplication1 E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
2020-04-05 03:31:35.077 5161-5219/com.example.testapplication1 E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-2
    Process: com.example.testapplication1, PID: 5161
    io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
        at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:76)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
        at co.chatsdk.core.utils.ImageBuilder$1.onFailureImpl(ImageBuilder.java:48)
        at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:57)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:172)
        at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:47)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:167)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:158)
        at com.facebook.datasource.AbstractDataSource.setFailure(AbstractDataSource.java:235)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onFailureImpl(AbstractProducerToDataSourceAdapter.java:85)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.access$000(AbstractProducerToDataSourceAdapter.java:28)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$1.onFailureImpl(AbstractProducerToDataSourceAdapter.java:57)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:410)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:504)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleError(DecodeProducer.java:379)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onFailureImpl(DecodeProducer.java:192)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:410)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:504)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onFailure(NetworkFetchProducer.java:183)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:33)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onFailure(NetworkFetchProducer.java:73)
2020-04-05 03:31:35.078 5161-5219/com.example.testapplication1 E/AndroidRuntime:     at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:94)
        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
      ComposedException 1 :
    	java.lang.Throwable: Unable to load image
        at co.chatsdk.core.utils.ImageBuilder$1.onFailureImpl(ImageBuilder.java:48)
        at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:57)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:172)
        at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:47)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:167)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:158)
        at com.facebook.datasource.AbstractDataSource.setFailure(AbstractDataSource.java:235)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onFailureImpl(AbstractProducerToDataSourceAdapter.java:85)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.access$000(AbstractProducerToDataSourceAdapter.java:28)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$1.onFailureImpl(AbstractProducerToDataSourceAdapter.java:57)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:410)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:504)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleError(DecodeProducer.java:379)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onFailureImpl(DecodeProducer.java:192)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:410)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:504)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onFailure(NetworkFetchProducer.java:183)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:33)
2020-04-05 03:31:35.078 5161-5219/com.example.testapplication1 E/AndroidRuntime:     at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onFailure(NetworkFetchProducer.java:73)
        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:94)
        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: The nextFunction returned a null SingleSource.
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:73)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
        at co.chatsdk.core.utils.ImageBuilder$1.onFailureImpl(ImageBuilder.java:48)
        at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:57)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:172)
        at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:47)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:167)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:158)
        at com.facebook.datasource.AbstractDataSource.setFailure(AbstractDataSource.java:235)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onFailureImpl(AbstractProducerToDataSourceAdapter.java:85)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.access$000(AbstractProducerToDataSourceAdapter.java:28)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$1.onFailureImpl(AbstractProducerToDataSourceAdapter.java:57)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:410)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:504)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleError(DecodeProducer.java:379)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onFailureImpl(DecodeProducer.java:192)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:410)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:504)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
2020-04-05 03:31:35.078 5161-5219/com.example.testapplication1 E/AndroidRuntime:     at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onFailure(NetworkFetchProducer.java:183)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:33)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onFailure(NetworkFetchProducer.java:73)
        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:94)
        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
      ComposedException 2 :
    	java.lang.NullPointerException: The nextFunction returned a null SingleSource.
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:73)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
        at co.chatsdk.core.utils.ImageBuilder$1.onFailureImpl(ImageBuilder.java:48)
        at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:57)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:172)
        at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:47)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:167)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:158)
        at com.facebook.datasource.AbstractDataSource.setFailure(AbstractDataSource.java:235)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onFailureImpl(AbstractProducerToDataSourceAdapter.java:85)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.access$000(AbstractProducerToDataSourceAdapter.java:28)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$1.onFailureImpl(AbstractProducerToDataSourceAdapter.java:57)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:410)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:504)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleError(DecodeProducer.java:379)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onFailureImpl(DecodeProducer.java:192)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
2020-04-05 03:31:35.078 5161-5219/com.example.testapplication1 E/AndroidRuntime:     at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:410)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:504)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onFailure(NetworkFetchProducer.java:183)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:33)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onFailure(NetworkFetchProducer.java:73)
        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:94)
        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-04-05 03:31:36.432 5161-5202/com.example.testapplication1 E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /259.png (No such file or directory)
```

**Comment by aymenhs** [comment]
I've the same errors too ! I tested with two physical devices (Android 8 on Huawei P10 lite , Android 10 on Huawei P10 lite and two emularos (android 10 & 9 ). I've always the same error when more than 2 users on a private chat.
I'll debug and if i find a solution will share.

**Comment by bensmiley** [comment]
Which version of the project are you using?

**Comment by aymenhs** [comment]
for me  4.8.5a4

**Comment by bensmiley** [comment]
The latest version is 4.8.9. The videos we public go out of date, so it's always best to look at the main project page.

**Comment by aymenhs** [comment]
as I'm adding chat sdk manually the only latest tagged version wasn't 4.8.9 ,where to find the code for  4.8.9 please?
https://github.com/chat-sdk/chat-sdk-android/releases/tag/4.8.5a4  is ok
BUT 
https://github.com/chat-sdk/chat-sdk-android/releases/tag/4.8.9   not ok

**Comment by bensmiley** [comment]
You could clone the repo to get the latest version or if you need a release you can useuse 4.8.12.

https://github.com/chat-sdk/chat-sdk-android/releases

**Comment by aymenhs** [comment]
ok I'll do and test ,thank you

**Comment by aymenhs** [comment]
I updated my project Ben to use 4.8.12 ,there're a regression when using : I created an issue
https://github.com/chat-sdk/chat-sdk-android/issues/613

**Comment by bjs007** [comment]
I tried with version 4.8.9 using 3 emulators. Apps are still crashing.

**Comment by aymenhs** [comment]
try with 4.8.12 it works fine :) private chat thread with 3 or more users

**Comment by bjs007** [comment]
With 4.8.12 it works for sometimes and crashes most of the time. I might be doing something wrong not sure what?

I am using MacBook with 8 GB RAM (if it matters).
Two emulators 
With API level 28, Android 9.0.
And one Motorola Phone Android 6.0

I am not using the push module.

These are my dependencies 
<p>


    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta4'

    implementation 'com.google.firebase:firebase-auth:19.3.0'
    implementation 'co.chatsdk.chatsdk:chat-sdk-firebase-adapter:4.8.12'
    implementation 'co.chatsdk.chatsdk:chat-sdk-firebase-file-storage:4.8.12'
    implementation 'co.chatsdk.chatsdk:chat-sdk-core:4.8.12'
    implementation 'co.chatsdk.chatsdk:chat-sdk-firebase-ui:4.8.12'
    implementation 'co.chatsdk.chatsdk:chat-sdk-ui:4.8.12'

    implementation 'com.android.support:multidex:2.0.1'


    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

<p>

.AppObject class

```
 @Override
    public void onCreate() {
        super.onCreate();
        Context context = getApplicationContext();
        try {
            Configuration config = new Configuration();

            ChatSDK.initialize(context, config, FirebaseNetworkAdapter.class, BaseInterfaceAdapter.class);

        } catch (ChatSDKException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

        FirebaseFileStorageModule.activate();
        FirebaseUIModule.activate(EmailAuthProvider.PROVIDER_ID, PhoneAuthProvider.PROVIDER_ID);
    }

I get bellow errors the 

```
2020-04-13 11:51:42.171 7089-7139/? E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
2020-04-13 11:51:43.043 7089-7089/com.ginfox.main E/EnhancedIntentService: binding to the service failed
2020-04-13 11:51:43.062 7089-7152/com.ginfox.main E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.ginfox.main, PID: 7089
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.Throwable: Unable to load image
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
        at co.chatsdk.core.utils.ImageBuilder$1.onFailureImpl(ImageBuilder.java:48)
        at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:57)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:172)
        at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:47)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:167)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:158)
        at com.facebook.datasource.AbstractDataSource.setFailure(AbstractDataSource.java:235)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onFailureImpl(AbstractProducerToDataSourceAdapter.java:104)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.access$000(AbstractProducerToDataSourceAdapter.java:29)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$1.onFailureImpl(AbstractProducerToDataSourceAdapter.java:76)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:420)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:527)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleError(DecodeProducer.java:408)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onFailureImpl(DecodeProducer.java:221)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onFailure(MultiplexProducer.java:420)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onFailureImpl(MultiplexProducer.java:527)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.DelegatingConsumer.onFailureImpl(DelegatingConsumer.java:26)
        at com.facebook.imagepipeline.producers.BaseConsumer.onFailure(BaseConsumer.java:110)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onFailure(NetworkFetchProducer.java:191)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:34)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onFailure(NetworkFetchProducer.java:81)
2020-04-13 11:51:43.062 7089-7152/com.ginfox.main E/AndroidRuntime:     at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:94)
        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.Throwable: Unable to load image
        	... 40 more

**Comment by aymenhs** [comment]
have you solved your problem?

**Comment by bjs007** [comment]
Nope.

**Comment by bensmiley** [comment]
We are about to release a new version of the library, version 5 which will fix all of these issues and has a lot of improvements. So it's not worth fixing this on v4. But a workaround is to add this:

```
RxJavaPlugins.setErrorHandler(throwable -> {
     throwable.printStackTrace();
});
```

Add this after calling ChatSDK.initialize. 

That will stop the app from crashing and print a stack trace instead.
