### ISSUE TITLE
Error while following tutorial

### ISSUE THREAD

**Issue by anarayn** [chat-sdk/chat-sdk-android#624]
1. **Is the bug present in the demo Chat SDK project?**
Not sure, I followed the steps described in turorial
2. **What modifications have you made to the Chat SDK?**
No changes, I did. 

```
val details = AccountDetails.token("custom firebase token");
      ChatSDK.auth().authenticate(details).subscribe(this::authSuccess, {
        Toast.makeText(applicationContext, "=========>Firebase Auth failed"+ it.message+"\n"+it.cause+"\n"+it.stackTrace,
          Toast.LENGTH_LONG)
      })
```

```
Ljava/lang/String;II)Landroid/graphics/Typeface; (light greylist, reflection)
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err: java.lang.reflect.InvocationTargetException
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err:     at co.chatsdk.core.session.ChatSDK.initialize(ChatSDK.java:86)
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err:     at com.app.nebyso.ui.SplashActivity.initChat(SplashActivity.kt:64)
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err:     at com.app.nebyso.ui.SplashActivity.onCreate(SplashActivity.kt:30)
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err:     at android.app.Activity.performCreate(Activity.java:7278)
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err:     at android.app.Activity.performCreate(Activity.java:7269)
2020-05-14 09:17:16.787 28639-28639/com.app.nebyso W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3159)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3314)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2018)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.os.Looper.loop(Looper.java:224)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7134)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err: Caused by: java.lang.BootstrapMethodError: Exception from call site #29 bootstrap method
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at co.chatsdk.core.events.NetworkEvent.filterType(NetworkEvent.java:184)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at co.chatsdk.firebase.FirebaseCoreHandler.<init>(FirebaseCoreHandler.java:53)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err:     at co.chatsdk.firebase.FirebaseNetworkAdapter.<init>(FirebaseNetworkAdapter.java:13)
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err: 	... 20 more
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err: Caused by: java.lang.ClassCastException: Bootstrap method returned null
2020-05-14 09:17:16.788 28639-28639/com.app.nebyso W/System.err: 	... 23 more

```
3. **Android Version:**
9, Funtouch OS_9.2. Getting a similar problem in other OS as well.
4. **Steps taken to reproduce the problem:**
Iny my main activity I am initializing chatsdk and then I get this error

```
private fun initChat(context: Context?) {
    try {
      // Create a new configuration
      val config = Configuration.Builder()

      // Perform any other configuration steps (optional)
      config.firebaseRootPath("prod")

      // Initialize the Chat SDK
      ChatSDK.initialize(
        context, config.build(),
        FirebaseNetworkAdapter::class.java, BaseInterfaceAdapter::class.java
      )
      config.publicRoomCreationEnabled(true);
      config.pushNotificationSound("default");
      config.pushNotificationsForPublicChatRoomsEnabled(false);

      config.setDevelopmentModeEnabled(true);
      config.debugModeEnabled(true)

      // For the demo version of the client expire rooms after 24 hours
            config.publicChatRoomLifetimeMinutes(60 * 24);
      config.publicChatRoomLifetimeMinutes(TimeUnit.HOURS.toMinutes(24));

      // File storage is needed for profile image upload and image messages
      FirebaseFileStorageModule.activate()

      // Push notification module
            FirebasePushModule.activate()

      // Activate any other modules you need.

            ProfilePicturesModule.activate();


      // Uncomment this to enable Firebase UI
      // FirebaseUIModule.activate(EmailAuthProvider.PROVIDER_ID, PhoneAuthProvider.PROVIDER_ID);


      // ...
      val details = AccountDetails.token("firebase custom token");
      ChatSDK.auth().authenticate(details).subscribe(this::authSuccess, {
        Toast.makeText(applicationContext, "=========>Firebase Auth failed"+ it.message+"\n"+it.cause+"\n"+it.stackTrace,
          Toast.LENGTH_LONG)
      })
            ChatSDK.ui().startSplashScreenActivity(applicationContext)
    } catch (e: Exception) {
      // Handle any exceptions
      e.printStackTrace()
    }

  }
  fun authSuccess(){
    Toast.makeText(applicationContext, "Firebase Auth success", Toast.LENGTH_LONG)
  }
```
5. **Expected result:**
Chat screen should have shown
6. **Actual result:**
I see my main activity loading
7. **Comments:**
Thanks for the help.

**Comment by bensmiley** [comment]
Are you actually using this code:
```
val details = AccountDetails.token("firebase custom token");
```
Because "Firebase custom token" is not a valid token. 

Also, you should set the config values before calling `ChatSDK.initialize`

You should also check to see if `ChatSDK.initialize` is throwing an error. 

Many thank
