### ISSUE TITLE
Crash at sdk.guru.realtime.RXRealtime$1.onCancelled(RXRealtime.java:65)

### ISSUE THREAD

**Issue by john-lq** [chat-sdk/chat-sdk-android#643]
Hello Team,

I have crashes on the following devices:
**Android Version:** 

- 6.0.1(Galaxy J7(2016))
- 7.0(X1)
- 7.1.2(Plume H1).
- 8.0.0(Galaxy S7 edge).
- 8.1.0(Galaxy J7 Prime, CPH1909).
- 9(Redmi 6A, Galaxy J7 Neo).
- 10(Galaxy A50, Galaxy A20s).
- and more

**Stack trace**
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
       at sdk.guru.realtime.RXRealtime$1.onCancelled(RXRealtime.java:65)
       at com.google.firebase.database.core.ValueEventRegistration.fireCancelEvent(com.google.firebase:firebase-database@@19.3.0:80)
       at com.google.firebase.database.core.view.CancelEvent.fire(com.google.firebase:firebase-database@@19.3.0:40)
       at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@19.3.0:55)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6269)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

I had a look on the `RXRealtime.java`. At line 65, the `ref` is accessed for the Log feature. And the `ref` variabl is also set to `null` in the `run()` method.
<img width="774" alt="Screen Shot 2020-08-03 at 17 13 40" src="https://user-images.githubusercontent.com/46557053/89177305-54fec100-d5b5-11ea-87ac-30126f8c8f4b.png">

I guess that the `run()` method is invoked before the code at line 65 is run.
Could you help me to check it?

Thanks,
John

**Comment by john-lq** [comment]
Hello Team,

Are there any update on this?

Thanks,
John
