### ISSUE TITLE
Null pointer exception on calling ChatSDK.auth()

### ISSUE THREAD

**Issue by MartPiet** [chat-sdk/chat-sdk-android#654]
1. **Is the bug present in the demo Chat SDK project?**
I guess no.

2. **What modifications have you made to the Chat SDK?**
None

3. **Android Version:**
10.0 (Emulator)

4. **Steps taken to reproduce the problem:**
Call ChatSDK.auth()

5. **Expected result:**
No crash

6. **Actual result:**
Crash

7. **Comments:**

Hey,

Currently I'm trying to manually sign in a user with a custom token. However, I found out that just calling ChatSDK.auth() crashes the app. I'm using the current ChatSDK version.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ..., PID: 8128
    java.lang.RuntimeException: Unable to start activity ComponentInfo{.../...MainActivity}: java.lang.NullPointerException: Attempt to read from field 'sdk.chat.core.handlers.AuthenticationHandler sdk.chat.core.base.BaseNetworkAdapter.auth' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'sdk.chat.core.handlers.AuthenticationHandler sdk.chat.core.base.BaseNetworkAdapter.auth' on a null object reference
        at sdk.chat.core.session.ChatSDK.auth(SourceFile:1)
        at ....MainActivity.signUpToChat(MainActivity.kt:65)
        at ....MainActivity.onCreate(MainActivity.kt:45)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

### Code:

```
fun signUpToChat() {
        val token = "[jwt-token]"
        val details = AccountDetails.token(token)
        ChatSDK.auth() // Crashes already
        ChatSDK.auth().authenticate(details).subscribe({ // Initial attempt to authenticate
            Log.i("Chat", "Authenticated")
        }, { error ->
            Log.e("Chat","error: $error")
        })
}
```

### My SDK configuration:

```
    private fun setUpChat() {
        try {
            val defaultBuild = ChatSDK.builder()
                .build()
                .addModule(
                    FirebaseModule.builder()
                        .setFirebaseRootPath("develop-android")
                        .setDisablePublicThreads(true)
                        .build()
                )
                .addModule(FirebasePushModule.shared())
                .addModule(
                    UIModule.builder()
                        .setPublicRoomCreationEnabled(false)
                        .setPublicRoomsEnabled(false)
                        .setLocationMessagesEnabled(false)
                        .setShowAvatarInChatView(false)
                        .setRequestPermissionsOnStartup(false)
                        .setGroupsEnabled(false)
                        .setImageMessagesEnabled(false)
                        .build()
                )
                .build()
                .activate(this)
        } catch (e: Exception) {
            e.printStackTrace()
        }
```

signUpToChat() is called immediately after setUpChat has finished.

### project build.gradle:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.4.0"
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        classpath "com.google.gms:google-services:4.3.3"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "http://dl.bintray.com/chat-sdk/chat-sdk-android" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

### app.gradle:

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlinx-serialization'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "..."
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        multiDexEnabled = true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.1.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
//    implementation 'com.google.firebase:firebase-database:19.4.0'
//    implementation 'com.google.firebase:firebase-crashlytics:17.2.1'

    implementation("io.reactivex.rxjava3:rxkotlin:3.0.0")
    implementation("io.reactivex.rxjava3:rxandroid:3.0.0")
    implementation("com.squareup.okhttp3:okhttp:4.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.0.0-RC")

    implementation "sdk.chat:firebase-app:5.0.9"
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "http://dl.bintray.com/chat-sdk/chat-sdk-android" }
    }
}
```

**Comment by MartPiet** [comment]
So I figured out, that the app does not crash using quickStart. Is something missing in my custom start setup?

**Comment by MartPiet** [comment]
The issue was that my custom start code was throwing an error. This error was thrown because my root path contained a "-" ("develop-android") which was not allowed and led to the error message:

`java.lang.Exception: The root path cannot contain special characters, they were removed so your new root path is: developandroid`

Of course - with no startup the auth() call failed.

This issue is fixed now.
