### ISSUE TITLE
co.chatsdk.core.handlers.PushHandler co.chatsdk.core.base.BaseNetworkAdapter.push' on a null object reference

### ISSUE THREAD

**Issue by mwaqassatti** [chat-sdk/chat-sdk-android#687]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?** Noting

3. **Android Version:** Android 6, Android 7

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

There are lot of crashes reported in firebase console.

Fatal Exception: java.lang.RuntimeException
Unable to start receiver co.chatsdk.core.push.DefaultBroadcastReceiver: java.lang.NullPointerException: Attempt to read from field 'co.chatsdk.core.handlers.PushHandler co.chatsdk.core.base.BaseNetworkAdapter.push' on a null object reference

Fatal Exception: java.lang.RuntimeException: Unable to start receiver co.chatsdk.core.push.DefaultBroadcastReceiver: java.lang.NullPointerException: Attempt to read from field 'co.chatsdk.core.handlers.PushHandler co.chatsdk.core.base.BaseNetworkAdapter.push' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2917)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at 

> java.lang.reflect.Method.invoke(Method.java)

       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

Caused by java.lang.NullPointerException
Attempt to read from field 'co.chatsdk.core.handlers.PushHandler co.chatsdk.core.base.BaseNetworkAdapter.push' on a null object reference
Caused by java.lang.NullPointerException: Attempt to read from field 'co.chatsdk.core.handlers.PushHandler co.chatsdk.core.base.BaseNetworkAdapter.push' on a null object reference
       at co.chatsdk.core.session.ChatSDK.push(ChatSDK.java:226)
       at co.chatsdk.core.push.DefaultBroadcastReceiver.onReceive(DefaultBroadcastReceiver.java:16)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2910)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

What is causing this issue, any would be really appreciated

**Comment by mwaqassatti** [comment]
@bensmiley

**Comment by bensmiley** [comment]
@mwaqassatti you need to have a push handler enabled. The reason why you are getting an issue is because it's not setup.

**Comment by bensmiley** [comment]
```
.addModule(FirebasePushModule.shared())
```

**Comment by mwaqassatti** [comment]
@bensmiley Thanks for your quick response. But what's minimum version to use .addModule()?
Currently we are using FirebasePushModule.activate() by using version 4.8.9.
