### ISSUE TITLE
Crash  in chatActivity xml files after update material lib into 1.3.0   in SDK version 4.8.3-5

### ISSUE THREAD

**Issue by mdhanifa460** [chat-sdk/chat-sdk-android#706]
SDK version ->  4.8.3-5

App force close while clicking chat group item from main screen . I don't know why it will impact to your package 

Bellow screens are working fine:
Main screen
Profile screen

Stack Trace

2021-06-07 19:03:50.323 18887-18887/com.ivy.sd.png.asean.view E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ivy.sd.png.asean.view, PID: 18887
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ivy.sd.png.asean.view/co.chatsdk.ui.chat.ChatActivity}: android.view.InflateException: Binary XML file line #37 in com.ivy.sd.png.asean.view:layout/abc_screen_toolbar: Binary XML file line #37 in com.ivy.sd.png.asean.view:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.Toolbar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: android.view.InflateException: Binary XML file line #37 in com.ivy.sd.png.asean.view:layout/abc_screen_toolbar: Binary XML file line #37 in com.ivy.sd.png.asean.view:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.Toolbar
     Caused by: android.view.InflateException: Binary XML file line #37 in com.ivy.sd.png.asean.view:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.Toolbar
got inflate exception in abc_screen_toolbar xml file
will able to find this xml fro that sdk

**Comment by bensmiley** [comment]
I'm afraid v4.x is no longer supported. So there's not really anything u can recommend other than updating to version 5.

**Comment by mdhanifa460** [comment]
thanks for update and i will migrate to version 5
