### ISSUE TITLE
Crashes when sending a message

### ISSUE THREAD

**Issue by Lavii7** [chat-sdk/chat-sdk-android#76]
After sending a message to another android device getting the below null exception crash:
`FATAL EXCEPTION: main
                                                                             Process: com.braunster.androidchatsdk.app, PID: 25229
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Boolean.toString()' on a null object reference
                                                                                 at com.braunster.androidchatsdk.firebaseplugin.firebase.BFirebaseNetworkAdapter$3.onDataChange(BFirebaseNetworkAdapter.java:332)
                                                                                 at com.google.firebase.database.Query$1.onDataChange(Unknown Source)`

it takes to this point when clicking on the BfirebaseNetworkAdapter.java:
 `  Timber.v(user.getEntityID() + ", " + user.getOnline().toString());`

**Comment by Lavii7** [comment]
Have downloaded and configured it according to the instruction provided; as to change no change other than the package name used everything else is the same.
