### ISSUE TITLE
Firebase Exception

### ISSUE THREAD

**Issue by melsayad** [chat-sdk/chat-sdk-android#82]
I faced this problem
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ktyna/com.braunster.chatsdk.activities.ChatSDKLoginActivity}: com.google.firebase.database.DatabaseException: Invalid URL (https://ktyna-cab15.firebaseio.com/testRoot/) passed to getReference().  URL was expected to match configured Database URL: https://chat-sdk-v4.firebaseio.com
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:154)
                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                          Caused by: com.google.firebase.database.DatabaseException: Invalid URL (https://ktyna-cab15.firebaseio.com/testRoot/) passed to getReference().  URL was expected to match configured Database URL: https://chat-sdk-v4.firebaseio.com
                                                             at com.google.firebase.database.FirebaseDatabase.getReferenceFromUrl(Unknown Source)
                                                             at com.braunster.androidchatsdk.firebaseplugin.firebase.FirebasePaths.fb(FirebasePaths.java:42)
                                                             at com.braunster.androidchatsdk.firebaseplugin.firebase.FirebasePaths.firebaseRef(FirebasePaths.java:37)
                                                             at com.braunster.androidchatsdk.firebaseplugin.firebase.FirebasePaths.userRef(FirebasePaths.java:48)
                                                             at com.braunster.androidchatsdk.firebaseplugin.firebase.FirebasePaths.userRef(FirebasePaths.java:53)
                                                             at com.braunster.androidchatsdk.firebaseplugin.firebase.FirebasePaths.userOnlineRef(FirebasePaths.java:63)
                                                             at com.braunster.androidchatsdk.firebaseplugin.firebase.wrappers.BUserWrapper.goOnline(BUserWrapper.java:443)
                                                             at com.braunster.androidchatsdk.firebaseplugin.firebase.BChatcatNetworkAdapter.setUserOnline(BChatcatNetworkAdapter.java:323)
                                                             at com.braunster.chatsdk.activities.ChatSDKBaseActivity.onStart(ChatSDKBaseActivity.java:233)
                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                             at android.app.Activity.performStart(Activity.java:6696)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:154) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
05-02 15:49:07.866 3023-3118/com.ktyna D/NetworkSecurityConfig: No Network Security Config specified, using platform default
05-02 15:49:10.929 3023-3030/com.ktyna W/art: Suspending all threads took: 7.127ms
05-02 15:49:17.442 3023-3044/com.ktyna E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.ktyna-1/base.apk", zip file "/data/app/com.ktyna-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.ktyna-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.ktyna-1/lib/x86, /system/lib, /vendor/lib]]
```

**Comment by simonsmiley64** [comment]
Hi @melsayad,

Can you provide more information on this issue.

For example when you download and compile the project without making any changes does it work?  

Looking at the error:

`Invalid URL (https://ktyna-cab15.firebaseio.com/testRoot/) passed to getReference(). URL was expected to match configured Database URL: https://chat-sdk-v4.firebaseio.com`

It looks like you haven't configured the Firebase account correctly. Have you gone through the [tutorial](https://github.com/chat-sdk/chat-sdk-android/wiki/Chat-SDK-Android:-Firebase-Configuration) or [tutorial video](https://www.youtube.com/watch?v=VZkLfXt_ibo).

Simon
