### ISSUE TITLE
Sample app crash on launch on android 4.4.2

### ISSUE THREAD

**Issue by Mohit001** [chat-sdk/chat-sdk-android#89]
05-17 01:26:25.210 3504-3504/com.braunster.androidchatsdk.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.braunster.androidchatsdk.app, PID: 3504
                                                                                java.lang.NoClassDefFoundError: com.android.tools.fd.runtime.AppInfo
                                                                                    at com.android.tools.fd.runtime.BootstrapApplication.<init>(BootstrapApplication.java:119)
                                                                                    at java.lang.Class.newInstanceImpl(Native Method)
                                                                                    at java.lang.Class.newInstance(Class.java:1208)
                                                                                    at android.app.Instrumentation.newApplication(Instrumentation.java:990)
                                                                                    at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                                    at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
                                                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
05-17 01:26:35.180 1587-1601/system_process E/WindowManager: Starting window AppWindowToken{b14bf1e0 token=Token{b13df6e8 ActivityRecord{b14321b0 u0 com.braunster.androidchatsdk.app/com.braunster.chatsdk.activities.ChatSDKLoginActivity t6}}} timed out

**Comment by simonsmiley64** [comment]
Hi @Mohit001,

Can you give us the details on when this crash occurs?

For example:
- Are you using a simulator?
- If you are using a phone what model and API is it using?
- What version of Android Studio are you using?
- What API are you using?
- When does the crash occur? On start up or when the activity tries to load?
- Have you modified the code in any way?

Once we know a bit more we can help troubleshoot as best possible,

Simon

**Comment by Mohit001** [comment]
hello Simon
i got sample apk link from below page
https://github.com/chat-sdk/chat-sdk-android

on click of sample apk link im redirected to below link
https://drive.google.com/file/d/0B5yzhtuipbsrYkl1Wkh2WjMwOEE/view

Initially im interested to see the functionality that ChatSDK is providing

i had download and install apk on my phone
device info
company : Micromax
Model : A310
Android Version : 4.4.2

after successfully install apk file when i launch application it just crash even i cant see splash/home screen i had connect my mobile to android studio and get error log trace which is already i had provide in last post

Thanks

**Comment by bensmiley** [comment]
We have now added a new APK of v4.0 which shouldn't crash.
