### ISSUE TITLE
app crashes on one device but not the other.

### ISSUE THREAD

**Issue by RogerRabbit91** [chat-sdk/chat-sdk-android#99]
The app works fine on the original account that I made that i have running on one device but on another testa count I have running on a separate device the app crashes when I try to sent anything. Below I will post the error message and the part of the code that is having the problem.
`06-02 13:27:17.017 6449-6449/com.braunster.androidchatsdk.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.braunster.androidchatsdk.app, PID: 6449
                                                                                java.lang.ClassCastException: java.util.HashMap cannot be cast to com.backendless.services.messaging.MessageStatus
                                                                                    at com.braunster.androidchatsdk.firebaseplugin.firebase.backendless.BBackendlessHandler$2.handleResponse(BBackendlessHandler.java:122)
                                                                                    at com.backendless.async.message.AsyncMessage$ResponseHandler.handle(AsyncMessage.java:64)
                                                                                    at com.backendless.async.message.AsyncMessage.handleCallback(AsyncMessage.java:41)
                                                                                    at com.backendless.core.AndroidCarrier$1.handleMessage(AndroidCarrier.java:37)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5944)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
06-02 13:31:17.767 6449-6459/com.braunster.androidchatsdk.app W/art: Suspending all threads took: 6.094ms

`            Backendless.Messaging.publish(channel, data.toString(), publishOptions, deliveryOptions, new AsyncCallback<MessageStatus>() {
                @Override
                public void handleResponse(MessageStatus response) {
                    if (DEBUG) Timber.v("Message published to channel: " + channel);
                }

                @Override
                public void handleFault(BackendlessFault fault) {
                    if (DEBUG) Timber.v("Publish failed, " + fault.getMessage());
                }
            });
        }
    }

**Comment by RogerRabbit91** [comment]
Maybe I have missed something when setting up the backendless account

**Comment by RogerRabbit91** [comment]
The message, pic, or location, sends it just crashes while doing so.

**Comment by RogerRabbit91** [comment]
bump

**Comment by matheuaviczki** [comment]
@Roger its crash if u send one or > 2 pic or location ? If > 2 the app crash because the loading...

**Comment by bensmiley** [comment]
Fixed in v4.0.
